// Corporate Mazdur — Hindi retro catalogue sourced from the supplied bus-driver site data.
// 133 Hindi song records. Playback uses the supplied YouTube video IDs via the official YouTube IFrame API.
const MOODS = [
  {id:'all',label:'All Songs',emoji:'✦'},
  {id:'morning',label:'Morning Coffee',emoji:'☕'},
  {id:'work',label:'Work Mode',emoji:'💻'},
  {id:'monday',label:'Monday Blues',emoji:'😭'},
  {id:'salary',label:'Salary Day',emoji:'💰'},
  {id:'romance',label:'Office Romance',emoji:'❤️'},
  {id:'ghazal',label:'Ghazal Night',emoji:'🌙'},
  {id:'rain',label:'Rain + Chai',emoji:'🌧'},
  {id:'friday',label:'Friday 5:59',emoji:'🕺'},
  {id:'commute',label:'Going Home',emoji:'🚗'},
  {id:'developer',label:'Developer Mazdur',emoji:'🧑\u200d💻'},
  {id:'latenight',label:'2AM Deployment',emoji:'🌃'},
  {id:'nostalgia',label:'90s Nostalgia',emoji:'📼'},
];
const CM_SONGS = [
  {
    slug: "chitthi-aayi-hai",
    year: 1986,
    hi: "चिट्ठी आई है",
    title: "Chitthi Aayi Hai",
    film: "Naam",
    artist: "Pankaj Udhas",
    videoId: "yexZf8g_dJw",
    fallbackVideoIds: ["xvFvsvUoss0", "v0_IRIFYC0k", "KCWy-7xyWXU", "CmUNrTakew0"],
    moods: ["monday", "latenight", "ghazal", "nostalgia", "morning", "rain"],
    artwork: "https://i.ytimg.com/vi/yexZf8g_dJw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=yexZf8g_dJw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ae-mere-humsafar",
    year: 1988,
    hi: "ऐ मेरे हमसफ़र",
    title: "Ae Mere Humsafar",
    film: "Qayamat Se Qayamat Tak",
    artist: "Udit Narayan",
    videoId: "sWqjZpBtcxc",
    moods: ["romance", "nostalgia", "morning", "ghazal"],
    artwork: "https://i.ytimg.com/vi/sWqjZpBtcxc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=sWqjZpBtcxc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "akele-hain-to-kya-gham-hai",
    year: 1988,
    hi: "अकेले हैं तो क्या ग़म है",
    title: "Akele Hain To Kya Gham Hai",
    film: "Qayamat Se Qayamat Tak",
    artist: "Udit Narayan",
    videoId: "QxpPkGSmCqY",
    moods: ["romance", "monday", "latenight", "developer", "salary", "nostalgia", "morning", "ghazal"],
    artwork: "https://i.ytimg.com/vi/QxpPkGSmCqY/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=QxpPkGSmCqY",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ek-do-teen",
    year: 1988,
    hi: "एक दो तीन",
    title: "Ek Do Teen",
    film: "Tezaab",
    artist: "Alka Yagnik",
    videoId: "MS5BLS2sIDM",
    moods: ["romance", "friday", "salary", "nostalgia", "morning", "ghazal"],
    artwork: "https://i.ytimg.com/vi/MS5BLS2sIDM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=MS5BLS2sIDM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "papa-kehte-hain",
    year: 1988,
    hi: "पापा कहते हैं",
    title: "Papa Kehte Hain",
    film: "Qayamat Se Qayamat Tak",
    artist: "Udit Narayan",
    videoId: "E8ytXrzkTNs",
    fallbackVideoIds: ["Yy0tnxRk87w"],
    moods: ["romance", "morning", "developer", "nostalgia", "ghazal"],
    artwork: "https://i.ytimg.com/vi/E8ytXrzkTNs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=E8ytXrzkTNs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-mera-janu-hai",
    year: 1988,
    hi: "तू मेरा जानू है",
    title: "Tu Mera Janu Hai",
    film: "Hero Hiralal",
    artist: "Amit Kumar",
    videoId: "rCRc0hHWMHQ",
    moods: ["nostalgia", "morning", "ghazal"],
    artwork: "https://i.ytimg.com/vi/rCRc0hHWMHQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=rCRc0hHWMHQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aate-jaate-haste-gaate",
    year: 1989,
    hi: "आते जाते हँसते गाते",
    title: "Aate Jaate Haste Gaate",
    film: "Maine Pyar Kiya",
    artist: "S. P. Balasubrahmanyam",
    videoId: "WGtqzK0VIRc",
    moods: ["romance", "morning", "commute", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/WGtqzK0VIRc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=WGtqzK0VIRc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dil-deewana",
    year: 1989,
    hi: "दिल दीवाना",
    title: "Dil Deewana",
    film: "Maine Pyar Kiya",
    artist: "Lata Mangeshkar",
    videoId: "rL-TT1uB3zc",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/rL-TT1uB3zc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=rL-TT1uB3zc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kabootar-ja-ja",
    year: 1989,
    hi: "कबूतर जा जा",
    title: "Kabootar Ja Ja",
    film: "Maine Pyar Kiya",
    artist: "S. P. Balasubrahmanyam",
    videoId: "do1cu32sWec",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/do1cu32sWec/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=do1cu32sWec",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "mere-rang-mein-rangne-wali",
    year: 1989,
    hi: "मेरे रंग में रंगने वाली",
    title: "Mere Rang Mein Rangne Wali",
    film: "Maine Pyar Kiya",
    artist: "S. P. Balasubrahmanyam",
    videoId: "BkLOBuTAtS0",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/BkLOBuTAtS0/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=BkLOBuTAtS0",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "oye-oye",
    year: 1989,
    hi: "ओए ओए",
    title: "Oye Oye",
    film: "Tridev",
    artist: "Vijeta Pandit",
    videoId: "lv4N9V5HjRA",
    moods: ["friday", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/lv4N9V5HjRA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=lv4N9V5HjRA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tirchi-topi-wale",
    year: 1989,
    hi: "तिरछी टोपी वाले",
    title: "Tirchi Topi Wale",
    film: "Tridev",
    artist: "Amit Kumar",
    videoId: "eYl9i8mH1lI",
    moods: ["nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/eYl9i8mH1lI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=eYl9i8mH1lI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ab-tere-bin-jee-lenge-hum",
    year: 1990,
    hi: "अब तेरे बिन जी लेंगे हम",
    title: "Ab Tere Bin Jee Lenge Hum",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "tUx-PDUKne8",
    moods: ["romance", "monday", "latenight", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/tUx-PDUKne8/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=tUx-PDUKne8",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "bas-ek-sanam-chahiye",
    year: 1990,
    hi: "बस एक सनम चाहिए",
    title: "Bas Ek Sanam Chahiye",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "G5sjHPy-SzU",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/G5sjHPy-SzU/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=G5sjHPy-SzU",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dheere-dheere-se-meri-zindagi",
    year: 1990,
    hi: "धीरे धीरे से मेरी ज़िंदगी",
    title: "Dheere Dheere Se Meri Zindagi",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "Mcs2xEZ6K8o",
    fallbackVideoIds: ["KeyfUuXPOcY", "pKsD2GiQhOo", "Y7QwlhOGZJI", "RYIspUp2hXA"],
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/Mcs2xEZ6K8o/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Mcs2xEZ6K8o",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jaane-jigar-jaaneman",
    year: 1990,
    hi: "जाने जिगर जानेमन",
    title: "Jaane Jigar Jaaneman",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "ecTeagAk1Dc",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/ecTeagAk1Dc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=ecTeagAk1Dc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jab-koi-baat-bigad-jaye",
    year: 1990,
    hi: "जब कोई बात बिगड़ जाए",
    title: "Jab Koi Baat Bigad Jaye",
    film: "Jurm",
    artist: "Kumar Sanu",
    videoId: "mNSYPtzpfd4",
    fallbackVideoIds: ["ln3meCI0LFM"],
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/mNSYPtzpfd4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=mNSYPtzpfd4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "main-duniya-bhula-doonga",
    year: 1990,
    hi: "मैं दुनिया भुला दूँगा",
    title: "Main Duniya Bhula Doonga",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "lmZVoOlzbxw",
    moods: ["romance", "monday", "latenight", "work", "developer", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/lmZVoOlzbxw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=lmZVoOlzbxw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "nazar-ke-samne",
    year: 1990,
    hi: "नज़र के सामने",
    title: "Nazar Ke Samne",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "A4_KJ8t-dbo",
    moods: ["romance", "monday", "latenight", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/A4_KJ8t-dbo/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=A4_KJ8t-dbo",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "saanson-ki-zaroorat-hai-jaise",
    year: 1990,
    hi: "साँसों की ज़रूरत है जैसे",
    title: "Saanson Ki Zaroorat Hai Jaise",
    film: "Aashiqui",
    artist: "Kumar Sanu",
    videoId: "YCuhzjK11iA",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/YCuhzjK11iA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YCuhzjK11iA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "bahut-pyar-karte-hain",
    year: 1991,
    hi: "बहुत प्यार करते हैं",
    title: "Bahut Pyar Karte Hain",
    film: "Saajan",
    artist: "Anuradha Paudwal",
    videoId: "iupGwQqjgOk",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/iupGwQqjgOk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=iupGwQqjgOk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dekha-hai-pehli-baar",
    year: 1991,
    hi: "देखा है पहली बार",
    title: "Dekha Hai Pehli Baar",
    film: "Saajan",
    artist: "S. P. Balasubrahmanyam",
    videoId: "bBjVLCAAM1A",
    moods: ["morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/bBjVLCAAM1A/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=bBjVLCAAM1A",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jaadu-bhari-aankhon-wali",
    year: 1991,
    hi: "जादू भरी आँखों वाली",
    title: "Jaadu Bhari Aankhon Wali",
    film: "Phool Aur Kaante",
    artist: "Kumar Sanu",
    videoId: "Q6JH5QMhGUc",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/Q6JH5QMhGUc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Q6JH5QMhGUc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jumma-chumma-de-de",
    year: 1991,
    hi: "जुम्मा चुम्मा दे दे",
    title: "Jumma Chumma De De",
    film: "Hum",
    artist: "Sudesh Bhosle",
    videoId: "bVzIHMskZmQ",
    moods: ["friday", "salary", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/bVzIHMskZmQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=bVzIHMskZmQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "mera-dil-bhi-kitna-pagal-hai",
    year: 1991,
    hi: "मेरा दिल भी कितना पागल है",
    title: "Mera Dil Bhi Kitna Pagal Hai",
    film: "Saajan",
    artist: "S. P. Balasubrahmanyam",
    videoId: "RVQsBlI35vw",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/RVQsBlI35vw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=RVQsBlI35vw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "saathiya-tune-kya-kiya",
    year: 1991,
    hi: "साथिया तूने क्या किया",
    title: "Saathiya Tune Kya Kiya",
    film: "Love",
    artist: "S. P. Balasubrahmanyam",
    videoId: "9J_isuHe8bw",
    moods: ["nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/9J_isuHe8bw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9J_isuHe8bw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tumse-milne-ki-tamanna",
    year: 1991,
    hi: "तुमसे मिलने की तमन्ना",
    title: "Tumse Milne Ki Tamanna",
    film: "Saajan",
    artist: "S. P. Balasubrahmanyam",
    videoId: "thjRNwjmAdQ",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/thjRNwjmAdQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=thjRNwjmAdQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aisi-deewangi",
    year: 1992,
    hi: "ऐसी दीवानगी",
    title: "Aisi Deewangi",
    film: "Deewana",
    artist: "Kumar Sanu",
    videoId: "_YjSmLlmqLM",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/_YjSmLlmqLM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=_YjSmLlmqLM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dhak-dhak-karne-laga",
    year: 1992,
    hi: "धक धक करने लगा",
    title: "Dhak Dhak Karne Laga",
    film: "Beta",
    artist: "Anuradha Paudwal",
    videoId: "AELvXURBfgw",
    moods: ["nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/AELvXURBfgw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=AELvXURBfgw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "koi-na-koi-chahiye",
    year: 1992,
    hi: "कोई न कोई चाहिए",
    title: "Koi Na Koi Chahiye",
    film: "Deewana",
    artist: "Kumar Sanu",
    videoId: "euZmH3dMDaE",
    moods: ["romance", "work", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/euZmH3dMDaE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=euZmH3dMDaE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "pehla-nasha",
    year: 1992,
    hi: "पहला नशा",
    title: "Pehla Nasha",
    film: "Jo Jeeta Wohi Sikandar",
    artist: "Udit Narayan",
    videoId: "Ki41AKu0iHc",
    fallbackVideoIds: ["bbGEUUvLRQw", "YoThngCrGGc", "L1lfXPKg304"],
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Ki41AKu0iHc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Ki41AKu0iHc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "roja-jaaneman",
    year: 1992,
    hi: "रोज़ा जानेमन",
    title: "Roja Jaaneman",
    film: "Roja",
    artist: "Hariharan",
    videoId: "PjiitGT4fUA",
    moods: ["romance", "commute", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/PjiitGT4fUA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=PjiitGT4fUA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "sochenge-tumhe-pyar",
    year: 1992,
    hi: "सोचेंगे तुम्हें प्यार",
    title: "Sochenge Tumhe Pyar",
    film: "Deewana",
    artist: "Kumar Sanu",
    videoId: "lFdSi01tpYM",
    moods: ["romance", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/lFdSi01tpYM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=lFdSi01tpYM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "teri-ummeed-tera-intezar",
    year: 1992,
    hi: "तेरी उम्मीद तेरा इंतज़ार",
    title: "Teri Ummeed Tera Intezar",
    film: "Deewana",
    artist: "Kumar Sanu",
    videoId: "xvevXfFGPFY",
    moods: ["romance", "monday", "latenight", "nostalgia", "morning"],
    artwork: "https://i.ytimg.com/vi/xvevXfFGPFY/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=xvevXfFGPFY",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "yeh-haseen-vadiyan",
    year: 1992,
    hi: "ये हसीन वादियाँ",
    title: "Yeh Haseen Vadiyan",
    film: "Roja",
    artist: "S. P. Balasubrahmanyam",
    videoId: "5kZ5o-oM0RI",
    moods: ["morning", "commute", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/5kZ5o-oM0RI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=5kZ5o-oM0RI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aaja-sajan-aaja",
    year: 1993,
    hi: "आजा सजन आजा",
    title: "Aaja Sajan Aaja",
    film: "Khal Nayak",
    artist: "Alka Yagnik",
    videoId: "v45d6MlNKIk",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/v45d6MlNKIk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=v45d6MlNKIk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "baazigar-o-baazigar",
    year: 1993,
    hi: "बाज़ीगर ओ बाज़ीगर",
    title: "Baazigar O Baazigar",
    film: "Baazigar",
    artist: "Kumar Sanu",
    videoId: "PUO7_Gi6ipg",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/PUO7_Gi6ipg/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=PUO7_Gi6ipg",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chhupana-bhi-nahi-aata",
    year: 1993,
    hi: "छुपाना भी नहीं आता",
    title: "Chhupana Bhi Nahi Aata",
    film: "Baazigar",
    artist: "Vinod Rathod",
    videoId: "X9MB_25XncQ",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/X9MB_25XncQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=X9MB_25XncQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "choli-ke-peeche",
    year: 1993,
    hi: "चोली के पीछे",
    title: "Choli Ke Peeche",
    film: "Khal Nayak",
    artist: "Ila Arun",
    videoId: "3OXiqmUhB70",
    moods: ["friday", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/3OXiqmUhB70/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=3OXiqmUhB70",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ghunghat-ki-aad-se",
    year: 1993,
    hi: "घूँघट की आड़ से",
    title: "Ghunghat Ki Aad Se",
    film: "Hum Hain Rahi Pyar Ke",
    artist: "Kumar Sanu",
    videoId: "xnhjxG79Ttc",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/xnhjxG79Ttc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=xnhjxG79Ttc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jaadu-teri-nazar",
    year: 1993,
    hi: "जादू तेरी नज़र",
    title: "Jaadu Teri Nazar",
    film: "Darr",
    artist: "Udit Narayan",
    videoId: "s_fdQXXDSLw",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/s_fdQXXDSLw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=s_fdQXXDSLw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kitaben-bahut-si",
    year: 1993,
    hi: "किताबें बहुत सी",
    title: "Kitaben Bahut Si",
    film: "Baazigar",
    artist: "Kumar Sanu",
    videoId: "ieu6xnwJxdA",
    moods: ["romance", "work", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/ieu6xnwJxdA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=ieu6xnwJxdA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "likha-hai-teri-aankhon-mein",
    year: 1993,
    hi: "लिखा है तेरी आँखों में",
    title: "Likha Hai Teri Aankhon Mein",
    film: "Darr",
    artist: "Kumar Sanu",
    videoId: "tfSqvusJiFI",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/tfSqvusJiFI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=tfSqvusJiFI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-mera-dil-tu-meri-jaan",
    year: 1993,
    hi: "तू मेरा दिल तू मेरी जान",
    title: "Tu Mera Dil Tu Meri Jaan",
    film: "Darr",
    artist: "Lata Mangeshkar",
    videoId: "Oj484P4OXD8",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Oj484P4OXD8/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Oj484P4OXD8",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-mere-samne",
    year: 1993,
    hi: "तू मेरे सामने",
    title: "Tu Mere Samne",
    film: "Darr",
    artist: "Lata Mangeshkar",
    videoId: "Oj484P4OXD8",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/Oj484P4OXD8/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Oj484P4OXD8",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "yeh-kaali-kaali-aankhen",
    year: 1993,
    hi: "ये काली काली आँखें",
    title: "Yeh Kaali Kaali Aankhen",
    film: "Baazigar",
    artist: "Kumar Sanu",
    videoId: "axtCauVo24M",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/axtCauVo24M/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=axtCauVo24M",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ae-kaash-ke-hum",
    year: 1994,
    hi: "ऐ काश के हम",
    title: "Ae Kaash Ke Hum",
    film: "Kabhi Haan Kabhi Naa",
    artist: "Kumar Sanu",
    videoId: "8RxkI28YxOk",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/8RxkI28YxOk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=8RxkI28YxOk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "churake-dil-mera",
    year: 1994,
    hi: "चुराके दिल मेरा",
    title: "Churake Dil Mera",
    film: "Main Khiladi Tu Anari",
    artist: "Kumar Sanu",
    videoId: "Yqj1_V90KJo",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Yqj1_V90KJo/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Yqj1_V90KJo",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "deewana-dil-deewana",
    year: 1994,
    hi: "दीवाना दिल दीवाना",
    title: "Deewana Dil Deewana",
    film: "Kabhi Haan Kabhi Naa",
    artist: "Kumar Sanu",
    videoId: "4bIQNbHofs0",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/4bIQNbHofs0/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=4bIQNbHofs0",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "didi-tera-devar-deewana",
    year: 1994,
    hi: "दीदी तेरा देवर दीवाना",
    title: "Didi Tera Devar Deewana",
    film: "Hum Aapke Hain Koun..!Lata Mangeshkar",
    artist: "",
    videoId: "mvlk8dJDuaA",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/mvlk8dJDuaA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=mvlk8dJDuaA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ek-ladki-ko-dekha",
    year: 1994,
    hi: "एक लड़की को देखा तो ऐसा लगा",
    title: "Ek Ladki Ko Dekha To Aisa Laga",
    film: "1942: A Love Story",
    artist: "Kumar Sanu",
    videoId: "htMvfOfixuM",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/htMvfOfixuM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=htMvfOfixuM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "is-tarah-aashiqui-ka",
    year: 1994,
    hi: "इस तरह आशिक़ी का",
    title: "Is Tarah Aashiqui Ka",
    film: "Imtihan",
    artist: "Kumar Sanu",
    videoId: "Y-o8NQ8Y36A",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Y-o8NQ8Y36A/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Y-o8NQ8Y36A",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kuch-na-kaho",
    year: 1994,
    hi: "कुछ न कहो",
    title: "Kuch Na Kaho",
    film: "1942: A Love Story",
    artist: "Kumar Sanu",
    videoId: "Kidtrrn4aUM",
    moods: ["romance", "work", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Kidtrrn4aUM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Kidtrrn4aUM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "lo-chali-main",
    year: 1994,
    hi: "लो चली मैं",
    title: "Lo Chali Main",
    film: "Hum Aapke Hain Koun..!Lata Mangeshkar",
    artist: "",
    videoId: "4o9wbyEOCdE",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/4o9wbyEOCdE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=4o9wbyEOCdE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "maine-pyar-tumhi-se-kiya-hai",
    year: 1994,
    hi: "मैंने प्यार तुम्हीं से किया है",
    title: "Maine Pyar Tumhi Se Kiya Hai",
    film: "Main Khiladi Tu Anari",
    artist: "Kumar Sanu",
    videoId: "FbCvF0aDgwA",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/FbCvF0aDgwA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=FbCvF0aDgwA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "maye-ni-maye",
    year: 1994,
    hi: "माये नी माये",
    title: "Maye Ni Maye",
    film: "Hum Aapke Hain Koun..!Lata Mangeshkar",
    artist: "",
    videoId: "XxSv6sDkOGM",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/XxSv6sDkOGM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=XxSv6sDkOGM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "na-kajre-ki-dhaar",
    year: 1994,
    hi: "ना कजरे की धार",
    title: "Na Kajre Ki Dhaar",
    film: "Mohra",
    artist: "Pankaj Udhas",
    videoId: "C_wxaIOPMZk",
    moods: ["ghazal", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/C_wxaIOPMZk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=C_wxaIOPMZk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "pehla-pehla-pyar-hai",
    year: 1994,
    hi: "पहला पहला प्यार है",
    title: "Pehla Pehla Pyar Hai",
    film: "Hum Aapke Hain Koun..!S. P. Balasubrahmanyam",
    artist: "",
    videoId: "HaO8tnM3u1U",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/HaO8tnM3u1U/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=HaO8tnM3u1U",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "pyar-hua-chupke-se",
    year: 1994,
    hi: "प्यार हुआ चुपके से",
    title: "Pyar Hua Chupke Se",
    film: "1942: A Love Story",
    artist: "Kavita Krishnamurthy",
    videoId: "iQMmyhezfg4",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/iQMmyhezfg4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=iQMmyhezfg4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "raah-mein-unse-mulaqat",
    year: 1994,
    hi: "राह में उनसे मुलाक़ात",
    title: "Raah Mein Unse Mulaqat",
    film: "Vijaypath",
    artist: "Kumar Sanu",
    videoId: "dDR4oiyjUBA",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/dDR4oiyjUBA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=dDR4oiyjUBA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "rim-jhim-rim-jhim",
    year: 1994,
    hi: "रिम झिम रिम झिम",
    title: "Rim Jhim Rim Jhim",
    film: "1942: A Love Story",
    artist: "Kumar Sanu",
    videoId: "nYdHqEyZpdk",
    moods: ["romance", "rain", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/nYdHqEyZpdk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=nYdHqEyZpdk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tip-tip-barsa-paani",
    year: 1994,
    hi: "टिप टिप बरसा पानी",
    title: "Tip Tip Barsa Paani",
    film: "Mohra",
    artist: "Udit Narayan",
    videoId: "Irr3fsN9G9c",
    moods: ["romance", "rain", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Irr3fsN9G9c/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Irr3fsN9G9c",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-cheez-badi-hai-mast",
    year: 1994,
    hi: "तू चीज़ बड़ी है मस्त मस्त",
    title: "Tu Cheez Badi Hai Mast Mast",
    film: "Mohra",
    artist: "Udit Narayan",
    videoId: "PufJm6BV8g4",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/PufJm6BV8g4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=PufJm6BV8g4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "yeh-mausam-ka-jadoo",
    year: 1994,
    hi: "ये मौसम का जादू",
    title: "Yeh Mausam Ka Jadoo",
    film: "Hum Aapke Hain Koun..!S. P. Balasubrahmanyam",
    artist: "",
    videoId: "B8iweNaBpis",
    moods: ["rain", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/B8iweNaBpis/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=B8iweNaBpis",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aankhon-mein-base-ho-tum",
    year: 1995,
    hi: "आँखों में बसे हो तुम",
    title: "Aankhon Mein Base Ho Tum",
    film: "Takkar",
    artist: "Kavita Krishnamurthy",
    videoId: "V3WrZcgeaoQ",
    moods: ["romance", "work", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/V3WrZcgeaoQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=V3WrZcgeaoQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aisa-zakhm-diya-hai",
    year: 1995,
    hi: "ऐसा ज़ख़्म दिया है",
    title: "Aisa Zakhm Diya Hai",
    film: "Akele Hum Akele Tum",
    artist: "Kumar Sanu",
    videoId: "3z7tf28mR90",
    moods: ["romance", "monday", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/3z7tf28mR90/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=3z7tf28mR90",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "akhiyaan-milaoon-kabhi",
    year: 1995,
    hi: "अखियाँ मिलाऊँ कभी",
    title: "Akhiyaan Milaoon Kabhi",
    film: "Raja",
    artist: "Udit Narayan",
    videoId: "QmEWg3P1GUQ",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/QmEWg3P1GUQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=QmEWg3P1GUQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dil-mera-churaya-kyun",
    year: 1995,
    hi: "दिल मेरा चुराया क्यों",
    title: "Dil Mera Churaya Kyun",
    film: "Akele Hum Akele Tum",
    artist: "Kumar Sanu",
    videoId: "JdDEVROAKjg",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/JdDEVROAKjg/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=JdDEVROAKjg",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "hai-rama",
    year: 1995,
    hi: "हाय रामा",
    title: "Hai Rama",
    film: "Rangeela",
    artist: "Hariharan",
    videoId: "3CM7aSOHc3Q",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/3CM7aSOHc3Q/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=3CM7aSOHc3Q",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ho-gaya-hai-tujhko",
    year: 1995,
    hi: "हो गया है तुझको तो प्यार सजना",
    title: "Ho Gaya Hai Tujhko To Pyar Sajna",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Lata Mangeshkar",
    videoId: "hw_HpTI_Wkw",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/hw_HpTI_Wkw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=hw_HpTI_Wkw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "humma-humma",
    year: 1995,
    hi: "हम्मा हम्मा",
    title: "Humma Humma",
    film: "Bombay",
    artist: "Remo Fernandes",
    videoId: "DJIkJEMjqfc",
    moods: ["friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/DJIkJEMjqfc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=DJIkJEMjqfc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jaati-hoon-main",
    year: 1995,
    hi: "जाती हूँ मैं",
    title: "Jaati Hoon Main",
    film: "Karan Arjun",
    artist: "Kumar Sanu",
    videoId: "l7iTcZ__Ejg",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/l7iTcZ__Ejg/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=l7iTcZ__Ejg",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kehna-hi-kya",
    year: 1995,
    hi: "कहना ही क्या",
    title: "Kehna Hi Kya",
    film: "Bombay",
    artist: "K. S. Chithra",
    videoId: "_YB1taxJPgk",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/_YB1taxJPgk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=_YB1taxJPgk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "mehndi-laga-ke-rakhna",
    year: 1995,
    hi: "मेहँदी लगा के रखना",
    title: "Mehndi Laga Ke Rakhna",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Udit Narayan",
    videoId: "hR-0OtU6gxw",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/hR-0OtU6gxw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=hR-0OtU6gxw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "mere-khwabon-mein-jo-aaye",
    year: 1995,
    hi: "मेरे ख़्वाबों में जो आए",
    title: "Mere Khwabon Mein Jo Aaye",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Lata Mangeshkar",
    videoId: "xF3gsIssLvM",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/xF3gsIssLvM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=xF3gsIssLvM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "nazrein-mili-dil-dhadka",
    year: 1995,
    hi: "नज़रें मिलीं दिल धड़का",
    title: "Nazrein Mili Dil Dhadka",
    film: "Raja",
    artist: "Udit Narayan",
    videoId: "wTuS2FFgrxs",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/wTuS2FFgrxs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=wTuS2FFgrxs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "raja-ko-rani-se-pyar-ho-gaya",
    year: 1995,
    hi: "राजा को रानी से प्यार हो गया",
    title: "Raja Ko Rani Se Pyar Ho Gaya",
    film: "Akele Hum Akele Tum",
    artist: "Udit Narayan",
    videoId: "aA6o96wkEt0",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/aA6o96wkEt0/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=aA6o96wkEt0",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ruk-ja-o-dil-deewane",
    year: 1995,
    hi: "रुक जा ओ दिल दीवाने",
    title: "Ruk Ja O Dil Deewane",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Udit Narayan",
    videoId: "jBpRItrod-Q",
    moods: ["romance", "work", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/jBpRItrod-Q/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=jBpRItrod-Q",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tanha-tanha",
    year: 1995,
    hi: "तनहा तनहा",
    title: "Tanha Tanha",
    film: "Rangeela",
    artist: "Asha Bhosle",
    videoId: "CKXG45s96m8",
    moods: ["monday", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/CKXG45s96m8/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=CKXG45s96m8",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-hi-re",
    year: 1995,
    hi: "तू ही रे",
    title: "Tu Hi Re",
    film: "Bombay",
    artist: "Hariharan",
    videoId: "V9mN0qBgEzQ",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/V9mN0qBgEzQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=V9mN0qBgEzQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tu-mile-dil-khile",
    year: 1995,
    hi: "तू मिले दिल खिले",
    title: "Tu Mile Dil Khile",
    film: "Criminal",
    artist: "Kumar Sanu",
    videoId: "nqTS7ngviwQ",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/nqTS7ngviwQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=nqTS7ngviwQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tujhe-dekha-to",
    year: 1995,
    hi: "तुझे देखा तो ये जाना सनम",
    title: "Tujhe Dekha To Ye Jaana Sanam",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Kumar Sanu",
    videoId: "cNV5hLSa9H8",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/cNV5hLSa9H8/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=cNV5hLSa9H8",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "zara-sa-jhoom-loon-main",
    year: 1995,
    hi: "ज़रा सा झूम लूँ मैं",
    title: "Zara Sa Jhoom Loon Main",
    film: "Dilwale Dulhania Le Jayenge",
    artist: "Abhijeet",
    videoId: "kjUTs76Gnks",
    moods: ["romance", "rain", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/kjUTs76Gnks/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=kjUTs76Gnks",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aaye-ho-meri-zindagi-mein",
    year: 1996,
    hi: "आए हो मेरी ज़िंदगी में",
    title: "Aaye Ho Meri Zindagi Mein",
    film: "Raja Hindustani",
    artist: "Udit Narayan",
    videoId: "ixCnsZswdpU",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/ixCnsZswdpU/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=ixCnsZswdpU",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chhod-aaye-hum",
    year: 1996,
    hi: "छोड़ आए हम वो गलियाँ",
    title: "Chhod Aaye Hum Woh Galiyan",
    film: "Maachis",
    artist: "Hariharan",
    videoId: "wGafZnT75a4",
    moods: ["monday", "latenight", "commute", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/wGafZnT75a4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=wGafZnT75a4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ghar-se-nikalte-hi",
    year: 1996,
    hi: "घर से निकलते ही",
    title: "Ghar Se Nikalte Hi",
    film: "Papa Kehte Hain",
    artist: "Udit Narayan",
    videoId: "_IcVb6hFhPs",
    moods: ["romance", "morning", "commute", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/_IcVb6hFhPs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=_IcVb6hFhPs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ho-nahi-sakta",
    year: 1996,
    hi: "हो नहीं सकता",
    title: "Ho Nahi Sakta",
    film: "Diljale",
    artist: "Kumar Sanu",
    videoId: "4_a0ge-TPJs",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/4_a0ge-TPJs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=4_a0ge-TPJs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jhanjhariya",
    year: 1996,
    hi: "झाँझरिया",
    title: "Jhanjhariya",
    film: "Krishna",
    artist: "Kumar Sanu",
    videoId: "vkF1PPHS99s",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/vkF1PPHS99s/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=vkF1PPHS99s",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kitna-pyara-tujhe",
    year: 1996,
    hi: "कितना प्यारा तुझे रब ने बनाया",
    title: "Kitna Pyara Tujhe Rab Ne Banaya",
    film: "Raja Hindustani",
    artist: "Udit Narayan",
    videoId: "tZqlD8VN9AE",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/tZqlD8VN9AE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=tZqlD8VN9AE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "pardesi-pardesi",
    year: 1996,
    hi: "परदेसी परदेसी",
    title: "Pardesi Pardesi",
    film: "Raja Hindustani",
    artist: "Udit Narayan",
    videoId: "xKb6lP3JxrA",
    moods: ["romance", "commute", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/xKb6lP3JxrA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=xKb6lP3JxrA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "are-re-are",
    year: 1997,
    hi: "अरे रे अरे",
    title: "Are Re Are",
    film: "Dil To Pagal Hai",
    artist: "Udit Narayan",
    videoId: "o31C53fu_so",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/o31C53fu_so/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=o31C53fu_so",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "bholi-si-surat",
    year: 1997,
    hi: "भोली सी सूरत",
    title: "Bholi Si Surat",
    film: "Dil To Pagal Hai",
    artist: "Udit Narayan",
    videoId: "-1J1XqOKnuw",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/-1J1XqOKnuw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=-1J1XqOKnuw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chand-taare",
    year: 1997,
    hi: "चाँद तारे",
    title: "Chand Taare",
    film: "Yes Boss",
    artist: "Abhijeet",
    videoId: "t3ynYlnIKAI",
    moods: ["rain", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/t3ynYlnIKAI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=t3ynYlnIKAI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dil-to-pagal-hai",
    year: 1997,
    hi: "दिल तो पागल है",
    title: "Dil To Pagal Hai",
    film: "Dil To Pagal Hai",
    artist: "Lata Mangeshkar",
    videoId: "ojCnlV1MA-k",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/ojCnlV1MA-k/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=ojCnlV1MA-k",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "do-dil-mil-rahe-hain",
    year: 1997,
    hi: "दो दिल मिल रहे हैं",
    title: "Do Dil Mil Rahe Hain",
    film: "Pardes",
    artist: "Kumar Sanu",
    videoId: "dReDtHKF0-g",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/dReDtHKF0-g/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=dReDtHKF0-g",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "duniya-haseeno-ka-mela",
    year: 1997,
    hi: "दुनिया हसीनों का मेला",
    title: "Duniya Haseeno Ka Mela",
    film: "Gupt",
    artist: "Udit Narayan",
    videoId: "S1Jnszqzfl4",
    moods: ["romance", "work", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/S1Jnszqzfl4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=S1Jnszqzfl4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "i-love-my-india",
    year: 1997,
    hi: "आई लव माय इंडिया",
    title: "I Love My India",
    film: "Pardes",
    artist: "Hariharan",
    videoId: "VHQ0w-9ITBI",
    moods: ["commute", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/VHQ0w-9ITBI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=VHQ0w-9ITBI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ke-ghar-kab-aaoge",
    year: 1997,
    hi: "के घर कब आओगे",
    title: "Ke Ghar Kab Aaoge",
    film: "Border",
    artist: "Sonu Nigam",
    videoId: "9sthJUHkzgI",
    moods: ["commute", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/9sthJUHkzgI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9sthJUHkzgI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "le-gayi",
    year: 1997,
    hi: "ले गई",
    title: "Le Gayi",
    film: "Dil To Pagal Hai",
    artist: "Asha Bhosle",
    videoId: "Qw0SM_TU20c",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Qw0SM_TU20c/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Qw0SM_TU20c",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "main-koi-aisa-geet-gaoon",
    year: 1997,
    hi: "मैं कोई ऐसा गीत गाऊँ",
    title: "Main Koi Aisa Geet Gaoon",
    film: "Yes Boss",
    artist: "Abhijeet",
    videoId: "vzlXfZlH5dk",
    moods: ["nostalgia", "work"],
    artwork: "https://i.ytimg.com/vi/vzlXfZlH5dk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=vzlXfZlH5dk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "meri-mehbooba",
    year: 1997,
    hi: "मेरी महबूबा",
    title: "Meri Mehbooba",
    film: "Pardes",
    artist: "Kumar Sanu",
    videoId: "k2CuG5E4OAo",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/k2CuG5E4OAo/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=k2CuG5E4OAo",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "neend-churai-meri",
    year: 1997,
    hi: "नींद चुराई मेरी",
    title: "Neend Churai Meri",
    film: "Ishq",
    artist: "Kumar Sanu",
    videoId: "gCcGXy_Mv8g",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/gCcGXy_Mv8g/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=gCcGXy_Mv8g",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "oonchi-hai-building",
    year: 1997,
    hi: "ऊँची है बिल्डिंग",
    title: "Oonchi Hai Building",
    film: "Judwaa",
    artist: "Abhijeet",
    videoId: "kcRiLuclqzo",
    moods: ["friday", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/kcRiLuclqzo/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=kcRiLuclqzo",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "sandese-aate-hain",
    year: 1997,
    hi: "संदेसे आते हैं",
    title: "Sandese Aate Hain",
    film: "Border",
    artist: "Sonu Nigam",
    videoId: "9sthJUHkzgI",
    moods: ["monday", "latenight", "commute", "developer", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/9sthJUHkzgI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9sthJUHkzgI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "sona-kitna-sona-hai",
    year: 1997,
    hi: "सोना कितना सोना है",
    title: "Sona Kitna Sona Hai",
    film: "Hero No. 1Poornima",
    artist: "",
    videoId: "PlN6oP-Nlno",
    moods: ["salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/PlN6oP-Nlno/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=PlN6oP-Nlno",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "yeh-dil-deewana",
    year: 1997,
    hi: "ये दिल दीवाना",
    title: "Yeh Dil Deewana",
    film: "Pardes",
    artist: "Sonu Nigam",
    videoId: "09DLlXKwJJU",
    moods: ["romance", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/09DLlXKwJJU/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=09DLlXKwJJU",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aankhon-se-tune-ye-kya",
    year: 1998,
    hi: "आँखों से तूने ये क्या कह दिया",
    title: "Aankhon Se Tune Ye Kya Keh Diya",
    film: "Ghulam",
    artist: "Kumar Sanu",
    videoId: "RlSRxyxFwXI",
    moods: ["romance", "work", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/RlSRxyxFwXI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=RlSRxyxFwXI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aati-kya-khandala",
    year: 1998,
    hi: "आती क्या खंडाला",
    title: "Aati Kya Khandala",
    film: "Ghulam",
    artist: "Aamir Khan",
    videoId: "EENnVk1_suc",
    moods: ["friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/EENnVk1_suc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=EENnVk1_suc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ae-ajnabi",
    year: 1998,
    hi: "ऐ अजनबी",
    title: "Ae Ajnabi",
    film: "Dil Se..",
    artist: "Udit Narayan",
    videoId: "D22u3A6S_Qk",
    moods: ["romance", "monday", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/D22u3A6S_Qk/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=D22u3A6S_Qk",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chaiyya-chaiyya",
    year: 1998,
    hi: "छैयाँ छैयाँ",
    title: "Chaiyya Chaiyya",
    film: "Dil Se..",
    artist: "Sukhwinder Singh",
    videoId: "9MX-QejdVaQ",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/9MX-QejdVaQ/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9MX-QejdVaQ",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "gali-mein-aaj-chand-nikla",
    year: 1998,
    hi: "गली में आज चाँद निकला",
    title: "Gali Mein Aaj Chand Nikla",
    film: "Zakhm",
    artist: "Alka Yagnik",
    videoId: "azEOf5PuqNA",
    moods: ["romance", "rain", "monday", "latenight", "morning", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/azEOf5PuqNA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=azEOf5PuqNA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "jiya-jale",
    year: 1998,
    hi: "जिया जले",
    title: "Jiya Jale",
    film: "Dil Se..",
    artist: "Lata Mangeshkar",
    videoId: "qaMQNwBhghA",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/qaMQNwBhghA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=qaMQNwBhghA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kisi-disco-mein-jaaye",
    year: 1998,
    hi: "किसी डिस्को में जाएँ",
    title: "Kisi Disco Mein Jaaye",
    film: "Bade Miyan Chote Miyan",
    artist: "Udit Narayan",
    videoId: "wfAIdZKs6Ok",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/wfAIdZKs6Ok/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=wfAIdZKs6Ok",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "koi-mil-gaya",
    year: 1998,
    hi: "कोई मिल गया",
    title: "Koi Mil Gaya",
    film: "Kuch Kuch Hota Hai",
    artist: "Udit Narayan",
    videoId: "IuS2d8bobgw",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/IuS2d8bobgw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=IuS2d8bobgw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kuch-kuch-hota-hai",
    year: 1998,
    hi: "कुछ कुछ होता है",
    title: "Kuch Kuch Hota Hai",
    film: "Kuch Kuch Hota Hai",
    artist: "Udit Narayan",
    videoId: "bKZTnnFU9HA",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/bKZTnnFU9HA/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=bKZTnnFU9HA",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ladki-badi-anjani-hai",
    year: 1998,
    hi: "लड़की बड़ी अनजानी है",
    title: "Ladki Badi Anjani Hai",
    film: "Kuch Kuch Hota Hai",
    artist: "Kumar Sanu",
    videoId: "oJcE_QPFAng",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/oJcE_QPFAng/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=oJcE_QPFAng",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "mere-mehboob-mere-sanam",
    year: 1998,
    hi: "मेरे महबूब मेरे सनम",
    title: "Mere Mehboob Mere Sanam",
    film: "Duplicate",
    artist: "Vinod Rathod",
    videoId: "p-pQaTOmVrs",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/p-pQaTOmVrs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=p-pQaTOmVrs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "satrangi-re",
    year: 1998,
    hi: "सतरंगी रे",
    title: "Satrangi Re",
    film: "Dil Se..",
    artist: "Sonu Nigam",
    videoId: "OClXVLsI4jM",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/OClXVLsI4jM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=OClXVLsI4jM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tujhe-yaad-na-meri-aayee",
    year: 1998,
    hi: "तुझे याद न मेरी आई",
    title: "Tujhe Yaad Na Meri Aayee",
    film: "Kuch Kuch Hota Hai",
    artist: "Udit Narayan",
    videoId: "vzWWTX83C_Q",
    moods: ["romance", "monday", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/vzWWTX83C_Q/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=vzWWTX83C_Q",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "aankhon-ki-gustakhiyan",
    year: 1999,
    hi: "आँखों की गुस्ताख़ियाँ",
    title: "Aankhon Ki Gustakhiyan",
    film: "Hum Dil De Chuke Sanam",
    artist: "Kumar Sanu",
    videoId: "2hpBJd-YcpI",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/2hpBJd-YcpI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=2hpBJd-YcpI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "albela-sajan",
    year: 1999,
    hi: "अलबेला साजन",
    title: "Albela Sajan",
    film: "Hum Dil De Chuke Sanam",
    artist: "Ustad Sultan Khan",
    videoId: "MCXQXuKpgKE",
    moods: ["romance", "ghazal", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/MCXQXuKpgKE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=MCXQXuKpgKE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chaha-hai-tujhko",
    year: 1999,
    hi: "चाहा है तुझको",
    title: "Chaha Hai Tujhko",
    film: "Mann",
    artist: "Udit Narayan",
    videoId: "9jpsuaZlIss",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/9jpsuaZlIss/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9jpsuaZlIss",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "chand-chupa-badal-mein",
    year: 1999,
    hi: "चाँद छुपा बादल में",
    title: "Chand Chupa Badal Mein",
    film: "Hum Dil De Chuke Sanam",
    artist: "Udit Narayan",
    videoId: "9a6UaCBEV6o",
    moods: ["romance", "rain", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/9a6UaCBEV6o/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=9a6UaCBEV6o",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dholi-taro-dhol-baaje",
    year: 1999,
    hi: "ढोली तारो ढोल बाजे",
    title: "Dholi Taro Dhol Baaje",
    film: "Hum Dil De Chuke Sanam",
    artist: "Vinod Rathod",
    videoId: "4a25J3p0kVI",
    moods: ["romance", "friday", "morning", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/4a25J3p0kVI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=4a25J3p0kVI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dilbar-dilbar",
    year: 1999,
    hi: "दिलबर दिलबर",
    title: "Dilbar Dilbar",
    film: "Sirf Tum",
    artist: "Alka Yagnik",
    videoId: "s5Iyc5rwUoI",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/s5Iyc5rwUoI/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=s5Iyc5rwUoI",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ghungroo-toot-gaye",
    year: 1999,
    hi: "घुंघरू टूट गए",
    title: "Ghungroo Toot Gaye",
    film: "Vaastav",
    artist: "Kumar Sanu",
    videoId: "69WKhXjWBNE",
    moods: ["romance", "friday", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/69WKhXjWBNE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=69WKhXjWBNE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "ishq-bina",
    year: 1999,
    hi: "इश्क़ बिना",
    title: "Ishq Bina",
    film: "Taal",
    artist: "Sonu Nigam",
    videoId: "SqZbGOCuai4",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/SqZbGOCuai4/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=SqZbGOCuai4",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "maiyya-yashoda",
    year: 1999,
    hi: "मैया यशोदा",
    title: "Maiyya Yashoda",
    film: "Hum Saath-Saath Hain",
    artist: "Alka Yagnik",
    videoId: "Kke1Q0J9quw",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/Kke1Q0J9quw/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=Kke1Q0J9quw",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "nimbooda",
    year: 1999,
    hi: "निम्बूड़ा",
    title: "Nimbooda",
    film: "Hum Dil De Chuke Sanam",
    artist: "Kavita Krishnamurthy",
    videoId: "YLsIl0G0qlM",
    moods: ["romance", "friday", "salary", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/YLsIl0G0qlM/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YLsIl0G0qlM",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "taal-se-taal-mila",
    year: 1999,
    hi: "ताल से ताल मिला",
    title: "Taal Se Taal Mila",
    film: "Taal",
    artist: "Udit Narayan",
    videoId: "OinGHNpnGtc",
    moods: ["romance", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/OinGHNpnGtc/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=OinGHNpnGtc",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "tadap-tadap",
    year: 1999,
    hi: "तड़प तड़प के",
    title: "Tadap Tadap Ke",
    film: "Hum Dil De Chuke Sanam",
    artist: "KK",
    videoId: "qsiHgJbwJUE",
    moods: ["romance", "monday", "latenight", "nostalgia"],
    artwork: "https://i.ytimg.com/vi/qsiHgJbwJUE/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=qsiHgJbwJUE",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "dil-ne-yeh-kaha-hai-dil-se",
    year: 2000,
    hi: "दिल ने ये कहा है दिल से",
    title: "Dil Ne Yeh Kaha Hai Dil Se",
    film: "Dhadkan",
    artist: "Udit Narayan",
    videoId: "dKLpCMfxB5U",
    moods: ["romance", "nostalgia", "salary", "commute"],
    artwork: "https://i.ytimg.com/vi/dKLpCMfxB5U/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=dKLpCMfxB5U",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  },
  {
    slug: "kaali-kaali-aankhen",
    year: 2001,
    hi: "काली काली आँखें",
    title: "Kaali Kaali Aankhen",
    film: "Chhupa Rustam",
    artist: "Sonu Nigam",
    videoId: "KI_EjpMxvJs",
    moods: ["work"],
    artwork: "https://i.ytimg.com/vi/KI_EjpMxvJs/hqdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=KI_EjpMxvJs",
    quote: "Corporate Mazdur approved. Pehle gaana, phir production."
  }
];
window.CM_SONGS = CM_SONGS;

// Optional verified alternates can be added here. The player tries them before moving
// to the next track. Keeping this as a map means the 133-song catalogue remains easy to edit.
const CM_FALLBACKS = {
  // Example: "song-slug": ["alternateVideoId1", "alternateVideoId2"]
};
for (const song of CM_SONGS) {
  song.fallbackVideoIds = CM_FALLBACKS[song.slug] || [];
}
